var app = angular.module('app', [])
app.controller('ctrl', function($scope){
	$scope.data = [
		//jepang
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-katsu-curry-rice.jpg",
                        nama:'Chicken Katsu Curry Rice',
                        jenis:'Nasi',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_ChickenKatsuCurryRice.html',
                },
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-sukiyaki-nabe.jpg",
                        nama:'Sukiyaki Nabe',
                        jenis:'Sukiyaki',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_SukiyakiNabe.html',
                },
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-spicy-tori-karaage.jpg",
                        nama:'Spicy Tori Karaage',
                        jenis:'Karaage',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_SpicyToriKaraage.html',
                },
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-miso-ramen.jpg",
                        nama:'Miso Ramen',
                        jenis:'Ramen',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_MisoRamen.html',
                },
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-sashimi-set.jpg",
                        nama:'Dr Sushi Sashimi Set',
                        jenis:'Sushi',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_DrSushiSashimiSet.html',
                },
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-volcano-roll.jpg",
                        nama:'Dr Sushi Volcano Roll',
                        jenis:'Sushi',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_DrSushiVolcanoRoll.html',
                },
                {
                        img:"../picture/japanese/Dr's-Sushi/dr-sushi-saba-shio-yaki.jpg",
                        nama:'Saba Shio Yaki',
                        jenis:'Ikan',
                        jalan:'Jl. Letjen S Parman No. 308, Medan',
                        url:'../item/japanese-item/makanan/DrsSushi_SabaShioYaki.html',
                },
                {
                        img:'../picture/japanese/Sushi Tei/MacaIceCream.jpg',
                        nama:'Maca Ice Cream',
                        jenis:'Ice Cream',
                        jalan:'Jl. Kh. Zainul Arifin No. 7, Sun Plaza LG A-01',
                        url:'../item/japanese-item/makanan/SushiTei_MacaIce.html',
                },
                {
                        img:'../picture/japanese/Sushi Tei/AburiSalmonRoll.jpg',
                        nama:'Aburi Salmon Roll',
                        jenis:'Sushi',
                        jalan:'Jl. Kh. Zainul Arifin No. 7, Sun Plaza LG A-01',
                        url:'../item/japanese-item/makanan/SushiTei_AburiSalmonRoll.html',
                },
                {
                        img:'../picture/japanese/Sushi Tei/CrunchyLobsterRoll.jpg',
                        nama:'Crunchy Lobster Roll',
                        jenis:'Sushi',
                        jalan:'Jl. Kh. Zainul Arifin No. 7, Sun Plaza LG A-01',
                        url:'../item/japanese-item/makanan/SushiTei_CrunchyLobster.html',
                },
                {
                        img:'../picture/japanese/Sushi Tei/GrilledChickenRamen.jpg',
                        nama:'Grilled Chicken Ramen',
                        jenis:'Ramen',
                        jalan:'Jl. Kh. Zainul Arifin No. 7, Sun Plaza LG A-01',
                        url:'../item/japanese-item/makanan/SushiTei_GrilledChicken.html',
                },
                {
                        img:'../picture/japanese/Sushi Tei/SalmonAburiCrispy.jpg',
                        nama:'Salmon Aburi Crispy',
                        jenis:'Sushi',
                        jalan:'Jl. Kh. Zainul Arifin No. 7, Sun Plaza LG A-01',
                        url:'../item/japanese-item/makanan/SushiTei_SalmonAburi.html',
                },
                {
                        img:'../picture/japanese/Sushi Tei/TunaSaladCrispyMentai.jpg',
                        nama:'Tuna Salad Crispy Mentai',
                        jenis:'Sushi',
                        jalan:'Jl. Kh. Zainul Arifin No. 7, Sun Plaza LG A-01',
                        url:'../item/japanese-item/makanan/SushiTei_TunaSalad.html',
                },
                {
                        img:'../picture/japanese/MarugameUdon/NikuUdon.jpg',
                        nama:'Niku Udon',
                        jenis:'Udon',
                        jalan:'Jl. Kh. Zainul Arifin No.7, Sun Plaza LG A-06,07,08',
                        url:'../item/japanese-item/makanan/MarugameUdon_NikuUdon.html',
                },
                {
                        img:'../picture/japanese/MarugameUdon/ZaruUdon.jpg',
                        nama:'Zaru Udon',
                        jenis:'Udon',
                        jalan:'Jl. Kh. Zainul Arifin No.7, Sun Plaza LG A-06,07,08',
                        url:'../item/japanese-item/makanan/MarugameUdon_ZaruUdon.html',
                },
                {
                        img:'../picture/japanese/MarugameUdon/ToriBaitangUdon.jpg',
                        nama:'Tori Baitang Udon',
                        jenis:'Udon',
                        jalan:'Jl. Kh. Zainul Arifin No.7, Sun Plaza LG A-06,07,08',
                        url:'../item/japanese-item/makanan/MarugameUdon_ToriBaitang.html',
                },
                {
                        img:'../picture/japanese/MarugameUdon/OntamaUdon.jpg',
                        nama:'Ontama Udon',
                        jenis:'Udon',
                        jalan:'Jl. Kh. Zainul Arifin No.7, Sun Plaza LG A-06,07,08',
                        url:'../item/japanese-item/makanan/MarugameUdon_OntamaUdon.html',
                },
                {
                        img:'../picture/japanese/Renjirokuu/renjiro-gyu-don.jpg',
                        nama:'Beef Teriyaki Don',
                        jenis:'Nasi',
                        jalan:'Jl. Jend. Gatot Subroto No. 30, Medan Fair Plaza 2nd Floor',
                        url:'../item/japanese-item/makanan/renjirokuu_BeefTeriyaki.html',
                },
                {
                        img:'../picture/japanese/Renjirokuu/renjirokuu-ramen.jpg',
                        nama:'Renjirokuu Chicken Ramen',
                        jenis:'Ramen',
                        jalan:'Jl. Jend. Gatot Subroto No. 30, Medan Fair Plaza 2nd Floor',
                        url:'../item/japanese-item/makanan/renjirokuu_ChickenRamen.html',
                },
                {
                        img:'../picture/japanese/Renjirokuu/renjirokuu-kani-roll.jpg',
                        nama:'Kani Roll & Shrimp Roll',
                        jenis:'Nasi',
                        jalan:'Jl. Jend. Gatot Subroto No. 30, Medan Fair Plaza 2nd Floor',
                        url:'../item/japanese-item/makanan/renjirokuu_kaniroll.html',
                },
                {
			img:'../picture/japanese/Renjirokuu/renjirokuu-spicy-yaki-ramen',
                        nama:'Spicy Yaki Ramen',
                        jenis:'Mie',
                        jalan:'Jl. Jend. Gatot Subroto No. 30, Medan Fair Plaza 2nd Floor',
                        url:'../item/japanese-item/makanan/renjirokuu_SpicyYakiRamen.html',
                },
	];
})